/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepak
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        adminText = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        addVehicle = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        unpark = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        vehicleOutbtn = new javax.swing.JButton();
        vehicleInbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizedBounds(new java.awt.Rectangle(30, 30, 1080, 800));
        setMaximumSize(new java.awt.Dimension(1080, 800));
        setMinimumSize(new java.awt.Dimension(1080, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        topPanel.setBackground(new java.awt.Color(29, 92, 150));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 92, 150)));
        topPanel.setForeground(new java.awt.Color(29, 92, 150));

        adminText.setFont(new java.awt.Font("Consolas", 1, 45)); // NOI18N
        adminText.setForeground(new java.awt.Color(255, 255, 255));
        adminText.setText("Admin");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(962, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(adminText)
                .addContainerGap())
        );

        getContentPane().add(topPanel);
        topPanel.setBounds(0, 0, 1110, 79);

        sidePanel.setBackground(new java.awt.Color(29, 92, 150));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 92, 150)));
        sidePanel.setForeground(new java.awt.Color(29, 92, 150));

        dashboard.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        dashboard.setForeground(new java.awt.Color(51, 51, 51));
        dashboard.setText("Dashboard");

        addVehicle.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        addVehicle.setForeground(new java.awt.Color(255, 255, 255));
        addVehicle.setText("Add Vehicle");
        addVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Consolas", 0, 32)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        unpark.setFont(new java.awt.Font("Consolas", 0, 23)); // NOI18N
        unpark.setForeground(new java.awt.Color(255, 255, 255));
        unpark.setText("Unpark Vehicle");
        unpark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unparkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unpark, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(logout))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addVehicle)))
                .addGap(6, 6, 6))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unpark, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(61, 61, 61))
        );

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 70, 210, 700);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setForeground(new java.awt.Color(0, 204, 102));

        vehicleOutbtn.setBackground(new java.awt.Color(246, 246, 246));
        vehicleOutbtn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        vehicleOutbtn.setText("Vehicle Out");
        vehicleOutbtn.setBorder(null);
        vehicleOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleOutbtnMouseClicked(evt);
            }
        });

        vehicleInbtn.setBackground(new java.awt.Color(246, 246, 246));
        vehicleInbtn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        vehicleInbtn.setText("Vehicle In");
        vehicleInbtn.setBorder(null);
        vehicleInbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleInbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(vehicleOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(vehicleInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(595, Short.MAX_VALUE)))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(vehicleOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(vehicleInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(572, Short.MAX_VALUE)))
        );

        getContentPane().add(centerPanel);
        centerPanel.setBounds(190, 80, 920, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleMouseClicked
        dispose();
        AddVehicle addVehicle = new AddVehicle();
    }//GEN-LAST:event_addVehicleMouseClicked

    private void vehicleInbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleInbtnMouseClicked
        dispose();
        VehicleIn vehicleIn = new VehicleIn();
    }//GEN-LAST:event_vehicleInbtnMouseClicked

    private void vehicleOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleOutbtnMouseClicked
        dispose();
        VehicleOut vehicleOut = new VehicleOut();
    }//GEN-LAST:event_vehicleOutbtnMouseClicked

    private void unparkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unparkMouseClicked
        dispose();
        Unpark unpark = new Unpark();
    }//GEN-LAST:event_unparkMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        Login login = new Login();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addVehicle;
    private javax.swing.JLabel adminText;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel unpark;
    private javax.swing.JButton vehicleInbtn;
    private javax.swing.JButton vehicleOutbtn;
    // End of variables declaration//GEN-END:variables
}
