
import java.awt.Color;
import javax.swing.BorderFactory;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepak
 */
public class Login extends javax.swing.JFrame {
    private String url = "jdbc:mysql://localhost:3306/vpmsdb";
    private String username = "root";
    private String password = "4213";
    private String dbPassword;
    private int checker=0;
    
    /**
     * Creates new form Splash
     */
    public Login() {
        initComponents();
        setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginSidepanel = new javax.swing.JPanel();
        vpmsLabel = new javax.swing.JLabel();
        vehicleIcon = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        loginForm = new javax.swing.JPanel();
        usernameTag = new javax.swing.JLabel();
        passwordTag = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(860, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        loginSidepanel.setBackground(new java.awt.Color(29, 92, 150));

        vpmsLabel.setFont(new java.awt.Font("Consolas", 1, 38)); // NOI18N
        vpmsLabel.setForeground(new java.awt.Color(255, 255, 255));
        vpmsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vpmsLabel.setText("VPMS");
        vpmsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vehicleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car-park (1).png"))); // NOI18N

        adminLabel.setFont(new java.awt.Font("Consolas", 0, 42)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setText("Admin Login");

        javax.swing.GroupLayout loginSidepanelLayout = new javax.swing.GroupLayout(loginSidepanel);
        loginSidepanel.setLayout(loginSidepanelLayout);
        loginSidepanelLayout.setHorizontalGroup(
            loginSidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSidepanelLayout.createSequentialGroup()
                .addGroup(loginSidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginSidepanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(vpmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginSidepanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(vehicleIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginSidepanelLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(adminLabel)
                .addGap(21, 21, 21))
        );
        loginSidepanelLayout.setVerticalGroup(
            loginSidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSidepanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(vehicleIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vpmsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminLabel)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        getContentPane().add(loginSidepanel);
        loginSidepanel.setBounds(0, 0, 311, 413);

        loginForm.setBackground(new java.awt.Color(255, 255, 255));

        usernameTag.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        usernameTag.setForeground(new java.awt.Color(29, 92, 150));
        usernameTag.setText("Username :-");

        passwordTag.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        passwordTag.setForeground(new java.awt.Color(29, 92, 150));
        passwordTag.setText("Password :-");

        usernameField.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        loginButton.setBackground(new java.awt.Color(29, 92, 150));
        loginButton.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setBorderPainted(false);
        loginButton.setName(""); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        javax.swing.GroupLayout loginFormLayout = new javax.swing.GroupLayout(loginForm);
        loginForm.setLayout(loginFormLayout);
        loginFormLayout.setHorizontalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passwordTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        loginFormLayout.setVerticalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTag)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordTag, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField))
                .addGap(52, 52, 52)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(loginForm);
        loginForm.setBounds(310, 0, 541, 407);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        try {
            checker=matchPassword();
            if(checker==1){
                usernameField.setText("Invalid Username and Password");
                return;
            }
            else{
            dispose();
            Dashboard dashboard = new Dashboard();
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private int matchPassword() throws Exception{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(url,username,password);
        CallableStatement stmt = con.prepareCall("{call getLoginData(?)}");
        stmt.setString(1, usernameField.getText());
        ResultSet set =  stmt.executeQuery();
        String passwordToHash = passwordField.getText().toString();
        String generatedPassword = null;
        while(set.next()){
            dbPassword=set.getString(1);
        }

        try
        {
            // Create MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // Add password bytes to digest
            md.update(passwordToHash.getBytes());

            // Get the hash's bytes
            byte[] bytes = md.digest();

            // This bytes[] has bytes in decimal format. Convert it to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }

            // Get complete hashed password in hex format
            generatedPassword = sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        if(dbPassword==null){
            return 1;
        }
        
        else if(dbPassword.equals(generatedPassword)){
            return 0;
        }
        
        
        
        
    
    return 1;
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPanel loginSidepanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordTag;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameTag;
    private javax.swing.JLabel vehicleIcon;
    private javax.swing.JLabel vpmsLabel;
    // End of variables declaration//GEN-END:variables
}
