import java.sql.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Deepak
 */
public class ParkVehicleDialog extends javax.swing.JDialog {

    /**
     * Creates new form ParkVehicleDialog
     */
    private String ownerNameString;
    private String ownerNumberString;
    private String RegistrationString;
    private String vCategoryString;
    private String vCompanyString;
    static String url = "jdbc:mysql://localhost:3306/vpmsdb";
    static String username = "root";
    static String password = "4213";
    private int i=0;
    
    
    
    public ParkVehicleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ParkVehicleDialog(){
        initComponents();
        i=1;
        vehicleData.setText("Please Enter All Data!!");
        setVisible(rootPaneCheckingEnabled);
    }
    public ParkVehicleDialog(String lownerNameString,String lownerNumberString,String lRegistrationString,String lvCategoryString,
    String lvCompanyString
    ){
        
        showData(lownerNameString, lownerNumberString, lRegistrationString, lvCategoryString, lvCompanyString);
        initComponents();
        printinTextArea();
        setVisible(rootPaneCheckingEnabled);
    }
    
    private void printinTextArea(){
        vehicleData.setText("Owner Name = "+ownerNameString+"\nOwner Mobile Number = "+ownerNumberString+"\nRegistration Number = "
                +RegistrationString+ "\nVehicle Category = "+vCategoryString+"\nVehicle Company = "+vCompanyString);
    }
    
    private void showData(String lownerNameString,String lownerNumberString,String lRegistrationString,String lvCategoryString,
    String lvCompanyString){
        ownerNameString = lownerNameString;
        ownerNumberString= lownerNumberString;
        RegistrationString = lRegistrationString;
        vCategoryString = lvCategoryString;
        vCompanyString = lvCompanyString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        confirmBtn.setBackground(new java.awt.Color(29, 92, 150));
        confirmBtn.setFont(new java.awt.Font("Consolas", 1, 34)); // NOI18N
        confirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmBtn.setText("Confirm");
        confirmBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmBtn.setBorderPainted(false);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(29, 92, 150));
        cancelBtn.setFont(new java.awt.Font("Consolas", 1, 34)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.setBorderPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        vehicleData.setEditable(false);
        vehicleData.setBackground(new java.awt.Color(255, 255, 255));
        vehicleData.setColumns(20);
        vehicleData.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        vehicleData.setRows(5);
        jScrollPane1.setViewportView(vehicleData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if(i==0){
        try {
            entryinDb();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(ParkVehicleDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            dispose();
        }
    }//GEN-LAST:event_confirmBtnActionPerformed
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void entryinDb() throws Exception{
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(url,username,password);
        CallableStatement stmt = con.prepareCall("{call myinsert(?,?,?,?,?,?)}");
        Integer random = ThreadLocalRandom.current().nextInt(0,50000);
        stmt.setInt(1, random);
        stmt.setString(2, vCategoryString);
        stmt.setString(3, vCompanyString);
        stmt.setString(4, RegistrationString);
        stmt.setString(5, ownerNameString);
        stmt.setString(6, ownerNumberString);
        stmt.execute();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ParkVehicleDialog dialog = new ParkVehicleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea vehicleData;
    // End of variables declaration//GEN-END:variables
}