
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Deepak
 */
public class Unpark extends javax.swing.JFrame {

    private String url = "jdbc:mysql://localhost:3306/vpmsdb";
    private String password = "4213";
    private String user = "root";
    private static Connection con;
    private static CallableStatement stmt;
    private String status;
    private int pnumber;
    public Unpark() {
        try {
            initComponents();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,user,password);
            setVisible(rootPaneCheckingEnabled);
        } catch (Exception ex) {
            Logger.getLogger(Unpark.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        adminText = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        unpark = new javax.swing.JLabel();
        addVehicle = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        unparkVehiclebtn = new javax.swing.JButton();
        parkingNo = new javax.swing.JLabel();
        parkingnoField = new javax.swing.JTextField();
        chargesField = new javax.swing.JTextField();
        parkingChargesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unpark Vehicle");
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(29, 92, 150));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 92, 150)));
        topPanel.setForeground(new java.awt.Color(29, 92, 150));

        adminText.setFont(new java.awt.Font("Consolas", 1, 45)); // NOI18N
        adminText.setForeground(new java.awt.Color(255, 255, 255));
        adminText.setText("Admin");

        sidePanel.setBackground(new java.awt.Color(29, 92, 150));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 92, 150)));
        sidePanel.setForeground(new java.awt.Color(29, 92, 150));

        dashboard.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        unpark.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        unpark.setForeground(new java.awt.Color(51, 51, 51));
        unpark.setText("Unpark Vehicle");

        addVehicle.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        addVehicle.setForeground(new java.awt.Color(255, 255, 255));
        addVehicle.setText("Add Vehicle");
        addVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Consolas", 0, 32)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unpark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addVehicle)
                            .addComponent(logout))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unpark)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(34, 34, 34))
        );

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setForeground(new java.awt.Color(0, 204, 102));

        unparkVehiclebtn.setBackground(new java.awt.Color(29, 92, 150));
        unparkVehiclebtn.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        unparkVehiclebtn.setForeground(new java.awt.Color(255, 255, 255));
        unparkVehiclebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minus.png"))); // NOI18N
        unparkVehiclebtn.setText("Remove Vehicle");
        unparkVehiclebtn.setBorderPainted(false);
        unparkVehiclebtn.setVerifyInputWhenFocusTarget(false);
        unparkVehiclebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unparkVehiclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unparkVehiclebtnActionPerformed(evt);
            }
        });

        parkingNo.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        parkingNo.setText("Parking Number");

        parkingnoField.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        chargesField.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        parkingChargesLabel.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        parkingChargesLabel.setText("Parking Charges");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parkingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingChargesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chargesField, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(unparkVehiclebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingnoField))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargesField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingChargesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(unparkVehiclebtn)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(adminText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unparkVehiclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unparkVehiclebtnActionPerformed
        try {
            
            int checker=checkforChar();
            int checker2=checkforChar2();
            
            if(parkingnoField.getText().isEmpty()||chargesField.getText().isEmpty()){
                return;
            }
            else if(checker==0||checker==1||checker2==0||checker2==1){
                UnparkVehicleDialog dialog = new UnparkVehicleDialog("invalid");
                return;
            }
            
            stmt = con.prepareCall("{call getDataUnpark(?)}");
            stmt.setInt(1, Integer.parseInt(parkingnoField.getText()));
            ResultSet set =  stmt.executeQuery();
            while(set.next()){
                pnumber = set.getInt(1);
            }
            
            if(pnumber==0){
                UnparkVehicleDialog dialog = new UnparkVehicleDialog("invalid");
            }
            
            else {
            stmt = con.prepareCall("{call getDataUnpark(?)}");
            stmt.setInt(1, Integer.parseInt(parkingnoField.getText()));
            set =  stmt.executeQuery();
            while(set.next()){
                status = set.getString(10);
            } 
            if(status==null){
                UnparkVehicleDialog dialog = new UnparkVehicleDialog(Integer.parseInt(parkingnoField.getText()),Integer.parseInt(chargesField.getText()));
            }
            else if(status.equals("out")){
                UnparkVehicleDialog dialog = new UnparkVehicleDialog();
            }
        }
     } catch (Exception ex) {
            Logger.getLogger(Unpark.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_unparkVehiclebtnActionPerformed

    private int checkforChar(){
        String pString = parkingnoField.getText();
        for(int i=0;i<pString.length();i++){
            for(char small='a';small<='z';small++){
                if(pString.charAt(i)==small)
                {
                    return 0;
                }
            }
            for(char capital='A';capital<='Z';capital++){
                if(pString.charAt(i)==capital)
                {
                    return 1;
                }
            }
        }
        return 2;
    }
    private int checkforChar2(){
        String pString = chargesField.getText();
        for(int i=0;i<pString.length();i++){
            for(char small='a';small<='z';small++){
                if(pString.charAt(i)==small)
                {
                    return 0;
                }
            }
            for(char capital='A';capital<='Z';capital++){
                if(pString.charAt(i)==capital)
                {
                    return 1;
                }
            }
        }
        return 2;
    }
    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
       dispose();
       Dashboard dashboard = new Dashboard();
       
    }//GEN-LAST:event_dashboardMouseClicked

    private void addVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleMouseClicked
        dispose();
        AddVehicle addVehicle = new AddVehicle();
    }//GEN-LAST:event_addVehicleMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        Login login = new Login();
    }//GEN-LAST:event_logoutMouseClicked

    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unpark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addVehicle;
    private javax.swing.JLabel adminText;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField chargesField;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel parkingChargesLabel;
    private javax.swing.JLabel parkingNo;
    private javax.swing.JTextField parkingnoField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel unpark;
    private javax.swing.JButton unparkVehiclebtn;
    // End of variables declaration//GEN-END:variables
}
