
import java.awt.MouseInfo;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Deepak
 */
public class UnparkVehicleDialog extends javax.swing.JDialog {
    private static CallableStatement stmtSetData;
    private static Connection con;
    private static CallableStatement stmtGetData;
    private String ownerNameString;
    private String ownerNumberString;
    private String RegistrationString;
    private String vCategoryString;
    private String vCompanyString;
    private Integer chargesField;
    private String url = "jdbc:mysql://localhost:3306/vpmsdb";
    private String password = "4213";
    private String user = "root";
    private Integer parkingnoField;
    private Integer i;
    
    public UnparkVehicleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public UnparkVehicleDialog(Integer parkingno,Integer chargeField) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,user,password);
            parkingnoField = parkingno;
            chargesField = chargeField;
            initComponents();
            printinTextArea();
            i=1;
            this.setVisible(rootPaneCheckingEnabled);
        } catch (Exception ex) {
            Logger.getLogger(UnparkVehicleDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public UnparkVehicleDialog(){
        initComponents();
        i=2;
        vehicleData.setText("Vehicle Already Unparked");
        this.setVisible(rootPaneCheckingEnabled);
    }
    public UnparkVehicleDialog(String mark){
        initComponents();
        i=3;
        vehicleData.setText("Invalid Entry");
        this.setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(MouseInfo.getPointerInfo().getLocation());
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        confirmBtn.setBackground(new java.awt.Color(29, 92, 150));
        confirmBtn.setFont(new java.awt.Font("Consolas", 1, 34)); // NOI18N
        confirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmBtn.setText("Confirm");
        confirmBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmBtn.setBorderPainted(false);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(29, 92, 150));
        cancelBtn.setFont(new java.awt.Font("Consolas", 1, 34)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.setBorderPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        vehicleData.setEditable(false);
        vehicleData.setBackground(new java.awt.Color(255, 255, 255));
        vehicleData.setColumns(20);
        vehicleData.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        vehicleData.setRows(5);
        jScrollPane1.setViewportView(vehicleData);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if(i==1){
        try {
            entryinDb();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(UnparkVehicleDialog.class.getName()).log(Level.SEVERE, null, ex);
        }}
        
        else if(i==2){
            dispose();
        }
        else{
            dispose();
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
         dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void printinTextArea() throws SQLException{
        stmtGetData = con.prepareCall("{call getDataUnpark(?)}");
        stmtGetData.setInt(1, parkingnoField);
        ResultSet set =  stmtGetData.executeQuery();
        while(set.next()){
        ownerNameString = set.getString(5);
        ownerNumberString = set.getString(6);
        RegistrationString = set.getString(4);
        vCategoryString = set.getString(2);
        vCompanyString = set.getString(1);
        }
        vehicleData.setText("Owner Name = "+ownerNameString+"\nOwner Mobile Number = "+ownerNumberString+"\nRegistration Number = "
                +RegistrationString+ "\nVehicle Category = "+vCategoryString+"\nVehicle Company = "+vCompanyString+ "\nParking Charges="+chargesField );
    }
    
    private void entryinDb() throws Exception{
        stmtSetData = con.prepareCall("{call unpark(?,?)}");
        stmtSetData.setInt(1, parkingnoField);
        stmtSetData.setInt(2, chargesField);
        stmtSetData.execute();
    }
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnparkVehicleDialog dialog = new UnparkVehicleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea vehicleData;
    // End of variables declaration//GEN-END:variables
}
